### ISSUE TITLE
Error loading file in boost 1.69.0

### ISSUE THREAD

**Issue by JLDDER** [daldegam/eos-portable-archive#4]
I can't find portable_binary_(i)oarchive in boost/archive.
so, I tried to copy those files in eos to boost/archive.
Then, it is different from tutorial, I can't use boost::archive::portable_binary_oarchive but eos::portable_oarchive could.
```
    template<class Archive>
    void Map::serialize(Archive &ar, const unsigned int version)
    {
        // don't save mutex
        ar & mspMapPoints;
        ar & mvpKeyFrameOrigins;
        ar & mspKeyFrames;
        ar & mvpReferenceMapPoints;
        ar & mnMaxKFid & mnBigChangeIdx;
        ar & mapScaleRatio;
    }
    template void Map::serialize(eos::portable_oarchive&, const unsigned int);
    template void Map::serialize(eos::portable_iarchive&, const unsigned int);
```
Next, when I compile code, it will show the warning:
**The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead**
Finally, It saved the file but I can't load it.

Help me find where wrong, thanks.

**Comment by romariorios** [comment]
I managed to create a minimal project that manages to reproduce this issue: [test-eos](https://github.com/romariorios/test-eos).

The problem happens during the **save**, _not_ the load, of the archive.

To reproduce the issue, I serialize a string. When trying to deserialize the string from the binary archive, nothing is loaded, as you described.

A few remarks:
- In my specific project, we're migrating to Conan. I thought that could have something to do with this issue, so I provided the options of either getting boost from conan.io or selecting your own pre-built boost. It didn't make a difference, so I quickly discarded this option.
- The exact same code, with no modifications, works as expected if the version is < 1.69. If boost is >= 1.69, the problem is reproduce -- up to and including boost 1.77.
- An archive saved with boost < 1.69 _can_ be opened with boost >= 1.69 with no issues, which indicates that the problem is in the _serialization_ -- the deserialization is fine.
- Analyzing the generated binary archives, I found out that the data is there in both archives, but the archive generated with the older boost starts with `7f01 1001 0d`, while the one generated with the newer boost starts with `7f01 0001 00`.

Some of my colleagues also dug into this problem and it seems that there's something corrupting the version header of the archive while the portable archive tries to save it (the version comes back as 0).

I hope this helps.
